### ISSUE TITLE
How to use this ?

### ISSUE THREAD

**Issue by Akirami** [nero120/cordova-plugin-icloud-document-storage#1]
Hello,

Could you please write some code on how to use your plugin ?

I'm stuck with this code 👍 

```
window.iCloudDocStorage.initUbiquitousContainer(cordova.file.syncedDataDirectory, function () {
   window.iCloudDocStorage.syncToCloud(cordova.file.documentsDirectory, function (val) {
    console.log(val)
  }, function (error) {
    console.log(error)
  })
}, function (err) {
  console.log( err)
})
```

**Comment by nero120** [comment]
Hi @Akirami, unfortunately I've moved away from iOS so haven't used this in a long time, I doubt it even still works with the current version of iOS. I should actually remove this repo as I really can't help, sorry.
